### ISSUE TITLE
Проблема с ветками и master

### ISSUE THREAD

**Issue by LetsPlayNow** [Garrus007/XtionScaner#5]
- [x] Сделай новые ветки под нововведения, когда будешь делать Pull 
  (сейчас стоковой является `create_pipeline`)
- [ ] Так же сделай merge с веткой `master`, чтоб она стала актуальной

:point_up:

**Comment by aemarkov** [comment]
Пока рано мерджить в мастер. Как будет что-то рабочее - тогда смерджим.
